---
- name: "Check required variables"
  assert:
    that: "{{ item.name }} is defined"
    fail_msg: "Missing variable '{{ item.name }}': {{ item.description }}"
  with_items:
    - { name: "service_id", description: "Id of the service instance that will be undeployed." }

- name: Install required pip modules
  pip:
    name:
      - jsonpatch
      - kubernetes>=17.17.0
      - PyYAML>=5.4.1
      - hvac>=1.0.2

- name: Read kubeconfig from Vault
  set_fact:
    kubeconfig: "{{ lookup('community.hashi_vault.hashi_vault', '{{ vault_lookup_base_info }} secret=resources/data/{{ resource_id }}:kubeconfig') }}"
  no_log: yes

- name: "Get info about namespace '{{ service_id }}'"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ service_id }}"
    kubeconfig: "{{ kubeconfig | from_yaml }}"
  register: info_output

- name: "Remove namespace"
  when: info_output.resources | length != 0
  kubernetes.core.k8s:
    name: "{{ service_id }}"
    api_version: v1
    kind: Namespace
    state: absent
    kubeconfig: "{{ kubeconfig | from_yaml }}"
    wait: yes
