---
- name: Converge - Kubeadm reset
  hosts: k8s_master[0]
  gather_facts: yes
  become: yes
  collections:
    - fabos.k8s
  tasks:
    - name: "Include fabos.k8s.setup - uninstall"
      include_role:
        name: setup
        tasks_from: uninstall.yml