---
- name: Get config from environment variables
  set_fact:
    consul_url: "{{ lookup('env', 'CONSUL_URL') }}"
    consul_token: "{{ lookup('env', 'CONSUL_TOKEN') }}"
    vault_url: "{{ lookup('env', 'VAULT_URL') }}"
    vault_approle_role_id: "{{ lookup('env', 'VAULT_APPROLE_ROLE_ID') }}"
    vault_approle_secret_id: "{{ lookup('env', 'VAULT_APPROLE_SECRET_ID') }}"
  no_log: true
- assert:
    that:
      - resource_to_add_id
      - (consul_url is defined) and (consul_url|length > 0)
      - (consul_token is defined) and (consul_token|length > 0)
      - (vault_url is defined) and (vault_url|length > 0)
      - (vault_approle_role_id is defined) and (vault_approle_role_id|length > 0)
      - (vault_approle_secret_id is defined) and (vault_approle_secret_id|length > 0)

- set_fact:
    vault_lookup_base_info: "url={{ vault_url }} auth_method=approle role_id={{ vault_approle_role_id }} secret_id={{ vault_approle_secret_id }}"


- set_fact:
    filter_exp: "{{ 'ID==\"' + resource_to_add_id + '\"' | urlencode() }}"

- name: "Get Node info of resource with id '{{ resource_to_add_id }}'"
  uri:
    url: "{{ consul_url }}/v1/catalog/nodes?filter={{ filter_exp }}"
    method: GET
    status_code: 200
    validate_certs: no
    headers:
      Authorization: "Bearer {{ consul_token }}"
  register: output_get_node

- set_fact:
    node_info: "{{ output_get_node.json | first }}"

- name: Set resource credentials
  set_fact:
    ip_address: "{{ node_info.Node }}"
    username: "{{ lookup('community.hashi_vault.hashi_vault', '{{ vault_lookup_base_info }} secret=resources/data/{{ resource_to_add_id }}:username') }}"
    password: "{{ lookup('community.hashi_vault.hashi_vault', '{{ vault_lookup_base_info }} secret=resources/data/{{ resource_to_add_id }}:password') }}"
  no_log: true

- name: Setup ansible inventory
  add_host:
    name: "{{ node_info.Address }}"
    groups:
      - target_host
      - k8s_node
    ansible_connection: ssh
    ansible_ssh_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
    ansible_become_pass: "{{ password }}"
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  no_log: true