- name: Set resource credentials
  set_fact:
    ip_address: "{{ item.Address }}"
    username: "{{ lookup('hashi_vault', '{{ vault_lookup_base_info }} secret=resources/data/{{ item.ID }}:username') }}"
    password: "{{ lookup('hashi_vault', '{{ vault_lookup_base_info }} secret=resources/data/{{ item.ID }}:password') }}"
  no_log: true


- name: Setup ansible inventory
  add_host:
    name: "{{ item.Address }}"
    groups: "{{ item.ServiceTags }}"
    ansible_connection: ssh
    ansible_ssh_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
    ansible_become_pass: "{{ password }}"
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  no_log: true
  changed_when: false